//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.13 at 02:41:30 PM MSK 
//


package by.it.korzik.jd02.jd02_09.beans;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Ad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ad">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CarType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FuelType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FuelPer100KM" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Doors" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *       &lt;attribute name="year" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ad", propOrder = {
    "model",
    "carType",
    "fuelType",
    "fuelPer100KM",
    "doors",
    "price"
})
public class Ad {

    @Override
    public String toString() {
        return "Ad{" +
                "model='" + model + '\'' +
                ", carType='" + carType + '\'' +
                ", fuelType='" + fuelType + '\'' +
                ", fuelPer100KM=" + fuelPer100KM +
                ", doors=" + doors +
                ", price=" + price +
                ", year=" + year +
                '}';
    }

    @XmlElement(name = "Model", required = true)
    protected String model;
    @XmlElement(name = "CarType", required = true)
    protected String carType;
    @XmlElement(name = "FuelType", required = true)
    protected String fuelType;
    @XmlElement(name = "FuelPer100KM")
    protected float fuelPer100KM;
    @XmlElement(name = "Doors", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger doors;
    @XmlElement(name = "Price", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger price;
    @XmlAttribute(name = "year", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger year;

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the carType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarType() {
        return carType;
    }

    /**
     * Sets the value of the carType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarType(String value) {
        this.carType = value;
    }

    /**
     * Gets the value of the fuelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * Sets the value of the fuelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelType(String value) {
        this.fuelType = value;
    }

    /**
     * Gets the value of the fuelPer100KM property.
     * 
     */
    public float getFuelPer100KM() {
        return fuelPer100KM;
    }

    /**
     * Sets the value of the fuelPer100KM property.
     * 
     */
    public void setFuelPer100KM(float value) {
        this.fuelPer100KM = value;
    }

    /**
     * Gets the value of the doors property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDoors() {
        return doors;
    }

    /**
     * Sets the value of the doors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDoors(BigInteger value) {
        this.doors = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPrice(BigInteger value) {
        this.price = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setYear(BigInteger value) {
        this.year = value;
    }

}
